Models/Driver.cs
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TrafikSkola.Models
{
    public class Driver
    {
        //public Driver(string driverName, string vechicalType, string fileName, byte[] file)
        //{
        //    DriverName = driverName;
        //    VechicalType = vechicalType;
        //    FileName = fileName;
        //    File = file;
        //}

        [Key]
        public int DriverId { get; set; }
        public string DriverName { get; set; }
        public string VechicalType { get; set; }

        

        public string FileName { get; set; }
        public byte[] File { get; set; }

        [NotMapped]
        public IFormFile FileForm { get; set; }
        public List<Learner> Learners { get; set; }
    }
}

Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TrafikSkola.Data;
using TrafikSkola.Models;

namespace TrafikSkola.Controllers
{
    [Authorize]
    public class BookingsController : Controller
    {
        private readonly ApplicationDbContext _context;
        public int Driverid { get; private set; }

        public BookingsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Bookings
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Bookings.Include(b => b.Driver).Include(b => b.Learner);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Bookings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .Include(b => b.Driver)
                .Include(b => b.Learner)
                .FirstOrDefaultAsync(m => m.BookingId == id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        // GET: Bookings/Create
        public IActionResult Create()
        {
            ViewData["DriverId"] = new SelectList(_context.Drivers, "DriverId", "DriverId");
            ViewData["LearnerId"] = new SelectList(_context.Learners, "LearnerId", "LearnerId");
            return View();
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BookingId,Start,End,DriverId,LearnerId")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                _context.Add(booking);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DriverId"] = new SelectList(_context.Drivers, "DriverId", "DriverId", booking.DriverId);
            ViewData["LearnerId"] = new SelectList(_context.Learners, "LearnerId", "LearnerId", booking.LearnerId);
            return View(booking);
        }

        // GET: Bookings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings.FindAsync(id);
            if (booking == null)
            {
                return NotFound();
            }
            ViewData["DriverId"] = new SelectList(_context.Drivers, "DriverId", "DriverId", booking.DriverId);
            ViewData["LearnerId"] = new SelectList(_context.Learners, "LearnerId", "LearnerId", booking.LearnerId);
            return View(booking);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BookingId,Start,End,DriverId,LearnerId")] Booking booking)
        {
            if (id != booking.BookingId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(booking);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookingExists(booking.BookingId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DriverId"] = new SelectList(_context.Drivers, "DriverId", "DriverId", booking.DriverId);
            ViewData["LearnerId"] = new SelectList(_context.Learners, "LearnerId", "LearnerId", booking.LearnerId);
            return View(booking);
        }

        // GET: Bookings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .Include(b => b.Driver)
                .Include(b => b.Learner)
                .FirstOrDefaultAsync(m => m.BookingId == id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var booking = await _context.Bookings.FindAsync(id);
            _context.Bookings.Remove(booking);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookingExists(int id)
        {
            return _context.Bookings.Any(e => e.BookingId == id);
        }
    }
}

Controllers/DriversController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TrafikSkola.Data;
using TrafikSkola.Models;

namespace TrafikSkola.Controllers
{
    public class DriversController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DriversController(ApplicationDbContext context)
        {
            _context = context;
        }
        
        // GET: Drivers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Drivers.ToListAsync());
        }

        // GET: Drivers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driver = await _context.Drivers
                .FirstOrDefaultAsync(m => m.DriverId == id);
            if (driver == null)
            {
                return NotFound();
            }

            return View(driver);
        }

        // GET: Drivers/Create
        [Authorize(Roles="Administator")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Drivers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DriverId,DriverName,VechicalType,FileName,File,FileForm")] Driver driver)
        {
            if (driver.FileForm != null)
            {
                byte[] bytes = null;
                using (MemoryStream ms = new MemoryStream())
                {
                    driver.FileForm.CopyTo(ms);
                    bytes = ms.ToArray();
                }

                driver.File = bytes;
                driver.FileName = driver.FileForm.FileName;
            }

            if (ModelState.IsValid)
            {
                _context.Add(driver);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(driver);
        }

        // GET: Drivers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driver = await _context.Drivers.FindAsync(id);
            if (driver == null)
            {
                return NotFound();
            }
            return View(driver);
        }

        // POST: Drivers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DriverId,DriverName,VechicalType,FileName,File")] Driver driver)
        {
            if (id != driver.DriverId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(driver);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DriverExists(driver.DriverId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(driver);
        }

        // GET: Drivers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driver = await _context.Drivers
                .FirstOrDefaultAsync(m => m.DriverId == id);
            if (driver == null)
            {
                return NotFound();
            }

            return View(driver);
        }

        // POST: Drivers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var driver = await _context.Drivers.FindAsync(id);
            _context.Drivers.Remove(driver);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DriverExists(int id)
        {
            return _context.Drivers.Any(e => e.DriverId == id);
        }
    }
}

Views/Drivers/Create.cshtml
@model TrafikSkola.Models.Driver

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Driver</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="Post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DriverName" class="control-label"></label>
                <input asp-for="DriverName" class="form-control" />
                <span asp-validation-for="DriverName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VechicalType" class="control-label"></label>
                <input asp-for="VechicalType" class="form-control" />
                <span asp-validation-for="VechicalType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FileName" class="control-label"></label>
                @*<input asp-for="FileName" class="form-control" />*@
                  <input type="File" onchange="getFile(this)" asp-for="FileName" name="FileForm" class="form-control" />

                
                <span asp-validation-for="FileName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="File" class="control-label"></label>
                @*<input asp-for="File" class="form-control" />*@
                  <img id="driverImage" height ="200"/>
                <span asp-validation-for="File" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
      <script>
        function getFile(data){
            //const image = document.querySelector('img');
            const image =document.getElementById('driverImage')
            const reader = new FileReader();
            const file =data.files[0];

            reader.addEventListener("load", function(){
            
                image.src = reader.result;
            },false);

            reader.readAsDataURL(file);
            
        }
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Drivers/Delete.cshtml
@model TrafikSkola.Models.Driver

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Driver</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DriverName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DriverName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VechicalType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VechicalType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FileName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FileName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.File)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.File)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="DriverId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Drivers/Details.cshtml
@model TrafikSkola.Models.Driver

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Driver</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DriverName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DriverName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VechicalType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VechicalType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FileName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FileName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.File)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.File)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.DriverId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Drivers/Edit.cshtml
@model TrafikSkola.Models.Driver

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Driver</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="DriverId" />
            <div class="form-group">
                <label asp-for="DriverName" class="control-label"></label>
                <input asp-for="DriverName" class="form-control" />
                <span asp-validation-for="DriverName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VechicalType" class="control-label"></label>
                <input asp-for="VechicalType" class="form-control" />
                <span asp-validation-for="VechicalType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FileName" class="control-label"></label>
                <input asp-for="FileName" class="form-control" />
                <span asp-validation-for="FileName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="File" class="control-label"></label>
                <input asp-for="File" class="form-control" />
                <span asp-validation-for="File" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Drivers/Index.cshtml
@model IEnumerable<TrafikSkola.Models.Driver>

@{
    ViewData["Title"] = "Index";
}
<body class="Driversbody">
<h1 style="Text-Align:center;">Welcome to Driver's page!</h1>
<hr />
<br />
<div class="row">
   @* <div class="col-md-6">
       <button type="button" class="btn btn-light btn-rounded"> <a asp-controller="Bookings">See Your Bookings here</a></button>
       </div>*@
      
       <div class="col-md-6">
         <button type="button" class="btn btn-light btn-rounded"> <a asp-action="Create">Add new Drivers here</a></button>
       </div>
</div>


  <!-- <a Response.Redirect(Url.Action("action", "Learnercontroller"))>see</a> -->
  <br />
  <hr />





@*<h1>Index</h1>*@

<p>
   @* <a asp-action="Create">Create New</a>*@
</p>
<table class="table table-hover">
    <thead>
        <tr class="p-3 mb-2 bg-dark text-white">
            <th>
                @Html.DisplayNameFor(model => model.DriverName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VechicalType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FileName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.File)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DriverName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VechicalType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FileName)
            </td>
            <td>
               @*@Html.DisplayFor(modelItem => item.File)*@
                 <img src="data:Image/jpeg;base64,@Convert.ToBase64String(item.File)"height="40"/>
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.DriverId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.DriverId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.DriverId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</body>